version: "3"
services:
  web:
    build: .
    restart: on-failure
    env_file:
      - ./.env
    command: poetry run gunicorn -c gunicorn.conf.py --access-logfile -
    volumes:
      - ./docker/volumes/postgres:/var/lib/postgresql/data
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: "postgres:14.2-alpine"
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
